language: perl
perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email "not-for-mail@travis-ci.org"
install:
    - cpanm --notest --skip-installed Dist::Zilla
    - dzil authordeps | grep -ve '^\\W' | xargs -n 5 -P 10 cpanm --notest --skip-installed
    - dzil listdeps | grep -ve '^\\W' | cpanm --notest --skip-installed
script: dzil test -j 3
